 CREATE TABLE `t_event` (
  `id_event` int(11) NOT NULL AUTO_INCREMENT COMMENT 'イベント情報ID',
  `date` date NOT NULL COMMENT '日付',
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'タイトル',
  `comment` text COLLATE utf8_unicode_ci NOT NULL COMMENT '記事',
  `image1` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像1',
  `image2` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像2',
  `image3` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像3',
  `image4` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像4',
  `image5` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像5',
  `image6` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '画像6',
  `caption1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション1',
  `caption2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション2',
  `caption3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション3',
  `caption4` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション4',
  `caption5` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション5',
  `caption6` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'キャプション6',
  `display_flg` tinyint(1) NOT NULL DEFAULT '0' COMMENT '表示フラグ',
  `display_indefinite` tinyint(1) NOT NULL DEFAULT '0' COMMENT '表示無期限フラグ',
  `display_start` datetime DEFAULT NULL COMMENT '掲載開始日',
  `display_end` datetime DEFAULT NULL COMMENT '掲載終了日',
  `entry_date` datetime NOT NULL COMMENT '登録日',
  `update_date` datetime DEFAULT NULL COMMENT '更新日',
  `subtitle` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'サブタイトル',
  `target` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '対象',
  `capacity` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '定員',
  `entry_fee` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '参加費',
  `venue` text COLLATE utf8_unicode_ci COMMENT '会場',
  `facility_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '施設名称',
  `location` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '所在地',
  `fee` text COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'ご利用料金',
  PRIMARY KEY (`id_event`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='イベント情報'